
name: 'DevOps MS teams webhook'
description: 'Send CI/CD notifications to MS teams'

inputs:
  webhook_url:
    default: ${{ secrets.WEBHOOK }}
    description: 'MS teams incoming webhook url'
    required: true
  job_status:
    default: ${{ job.status }}
    description: 'The current status of the job. Possible values are success, failure, or cancelled'
    required: true
  job_name:
    default: ${{ github.job }}
    description: 'The name of the current job'
    required: true
  REPOSITORY_NAME: 
    default: ${{ github.event.repository.name }}
  REPOSITORY_URL: 
    default: ${{ github.repository }}
  EVENT: 
    default: ${{ github.event_name }}  
  BRANCH: 
    default: ${{github.event.pull_request.head.ref}}
  ACTOR: 
    default: ${{ github.actor }}
  PR_NUMBER: 
    default: ${{ github.event.pull_request.number }}
  RUN_ID: 
    default: ${{ github.run_id }}

runs:
  using: 'docker'
  image: 'Dockerfile'
