
name: 'DevOps MS Teams webhook'
description: 'Send CI/CD notifications to MS Teams'

inputs:
    cpu: 
      description: 'Determines which Docker image to use based on CPU architecture. Possible values: arm64, arm64'
      required: false

runs:
  using: 'Docker'
  image: 'Dockerfile'
 
