
name: 'DevOps MS Teams webhook'
description: 'Send CI/CD notifications to MS Teams'

inputs:
    cpu: 
      description: 'Determines which Docker image to use based on CPU architecture. Possible values: arm64, arm64'
      required: true
env:
    mike: ${{ inputs.cpu}}
runs:
  using: 'Docker'
  image: $mike
 
